import { DEFAULT_LIMITS } from "./defaults.ts";
import { sanitizeRelativePath } from "./names.ts";
import { CAPABILITIES, type Capability, type FileSignal } from "./protocol.ts";

export type ParseLimits = {
  maxFileBytes: number;
  maxNameChars: number;
  maxMimeChars: number;
  maxSdpChars: number;
  maxReasonChars: number;
  maxPathChars: number;
};

export const DEFAULT_PARSE_LIMITS: ParseLimits = {
  maxFileBytes: DEFAULT_LIMITS.maxFileBytes,
  maxNameChars: 255,
  maxMimeChars: 255,
  maxSdpChars: 24 * 1024,
  maxReasonChars: 200,
  maxPathChars: 1024,
};

const MIN_ID_CHARS = 8;
const MAX_ID_CHARS = 64;
const ID_PATTERN = /^[A-Za-z0-9_-]+$/;

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isBoundedString(value: unknown, max: number): value is string {
  return typeof value === "string" && value.length > 0 && value.length <= max;
}

function isOptionalNullable<T>(value: unknown, check: (v: unknown) => v is T) {
  return value === undefined || value === null || check(value);
}

const MAX_CAPS = 8;

/**
 * Known capabilities from a peer's list, or undefined. Lenient on purpose: a
 * newer peer may advertise features this version doesn't know, and a bad list
 * should cost the feature, not the whole signal.
 */
function parseCaps(value: unknown): Capability[] | undefined {
  if (!Array.isArray(value) || value.length > MAX_CAPS) {
    return undefined;
  }
  const caps = CAPABILITIES.filter((cap) => value.includes(cap));
  return caps.length > 0 ? caps : undefined;
}

/** Ids are generated by `createRandomId` (or your `createId`), never free text. */
export function isValidId(value: unknown): value is string {
  return (
    typeof value === "string" &&
    value.length >= MIN_ID_CHARS &&
    value.length <= MAX_ID_CHARS &&
    ID_PATTERN.test(value)
  );
}

/**
 * Rebuilds a signal from only the fields the protocol defines, or returns null.
 *
 * Signals come from other peers, so treat them as untrusted: run everything
 * that arrives off the wire through this before `handleSignal`. `peer-left` is
 * always rejected, because a peer must not be able to claim another one left.
 */
export function parseFileSignal(
  input: unknown,
  limits: Partial<ParseLimits> = {},
): FileSignal | null {
  const max = { ...DEFAULT_PARSE_LIMITS, ...limits };
  if (!isRecord(input)) {
    return null;
  }

  switch (input.type) {
    case "hello":
      return { type: "hello" };

    case "file-offer": {
      const { offerId, name, size, mime } = input;
      if (
        !isValidId(offerId) ||
        !isBoundedString(name, max.maxNameChars) ||
        typeof size !== "number" ||
        !Number.isSafeInteger(size) ||
        size <= 0 ||
        size > max.maxFileBytes ||
        !(typeof mime === "string" && mime.length <= max.maxMimeChars)
      ) {
        return null;
      }
      const caps = parseCaps(input.caps);
      const path =
        isBoundedString(input.path, max.maxPathChars) && sanitizeRelativePath(input.path);
      return {
        type: "file-offer",
        offerId,
        name,
        size,
        mime,
        ...(caps && { caps }),
        ...(path && { path }),
        ...(isValidId(input.batchId) && { batchId: input.batchId }),
      };
    }

    case "file-revoke":
      return isValidId(input.offerId)
        ? { type: "file-revoke", offerId: input.offerId }
        : null;

    case "file-request": {
      const { offerId, transferId, offset } = input;
      if (!isValidId(offerId) || !isValidId(transferId)) {
        return null;
      }
      const caps = parseCaps(input.caps);
      return {
        type: "file-request",
        offerId,
        transferId,
        ...(caps && { caps }),
        // The sender checks the offset against the file's real size.
        ...(typeof offset === "number" &&
        Number.isSafeInteger(offset) &&
        offset > 0 &&
        offset <= max.maxFileBytes
          ? { offset }
          : {}),
      };
    }

    case "rtc-description": {
      const { transferId, description } = input;
      if (
        !isValidId(transferId) ||
        !isRecord(description) ||
        (description.type !== "offer" && description.type !== "answer") ||
        !isBoundedString(description.sdp, max.maxSdpChars)
      ) {
        return null;
      }
      return {
        type: "rtc-description",
        transferId,
        description: { type: description.type, sdp: description.sdp },
      };
    }

    case "rtc-candidate": {
      const { transferId, candidate } = input;
      if (
        !isValidId(transferId) ||
        !isRecord(candidate) ||
        typeof candidate.candidate !== "string" ||
        candidate.candidate.length > 1024 ||
        !isOptionalNullable(candidate.sdpMid, (v): v is string =>
          isBoundedString(v, MAX_ID_CHARS),
        ) ||
        !isOptionalNullable(candidate.sdpMLineIndex, (v): v is number =>
          typeof v === "number" && Number.isInteger(v) && v >= 0,
        ) ||
        !isOptionalNullable(candidate.usernameFragment, (v): v is string =>
          isBoundedString(v, 256),
        )
      ) {
        return null;
      }
      return {
        type: "rtc-candidate",
        transferId,
        candidate: {
          candidate: candidate.candidate,
          sdpMid: candidate.sdpMid as string | null | undefined,
          sdpMLineIndex: candidate.sdpMLineIndex as number | null | undefined,
          usernameFragment: candidate.usernameFragment as string | null | undefined,
        },
      };
    }

    case "transfer-cancel":
      return isValidId(input.transferId) &&
        isBoundedString(input.reason, max.maxReasonChars)
        ? { type: "transfer-cancel", transferId: input.transferId, reason: input.reason }
        : null;

    default:
      return null;
  }
}
